### ISSUE TITLE
mongoose.connect(process.env.MONGO_URL, {server:{auto_reconnect:true}});

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [huseyinbabal/nodes-restful-api#1]
mongoose.connect(process.env.MONGO_URL, {server:{auto_reconnect:true}});

How to proceed to connect to mongodb?

**Comment by huseyinbabal** [comment]
This is invalid issue, and couldn't understand what you are trying to do. Refer [here](https://github.com/huseyinbabal/nodes-restful-api/blob/master/app/core/mongoose.js) to learn anything anyway
