### ISSUE TITLE
Where is the mongo database information ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [huseyinbabal/nodes-restful-api#4]
C:\Users\alotfi\nodeJS\nodes-restful-api>node server.js

App is ready at : 3000

MongoDB disconnected!

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

MongoDB disconnected!

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

MongoDB disconnected!

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

MongoDB disconnected!

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

^C

C:\Users\alotfi\nodeJS\nodes-restful-api>

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

MongoDB disconnected!

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

MongoDB disconnected!

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

MongoDB disconnected!

MongoDB connection error: [Error: failed to connect to [undefined:27017]]

MongoDB disconnected!

**Comment by huseyinbabal** [comment]
You have to set MONGO_URL in environment settings
